onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@sentry-internal/node-native-stacktrace'
  - cpu-features
  - msgpackr-extract
  - oracledb
  - protobufjs
  - sqlite3
  - ssh2
packages:
  - 'sidecar-app/n8n'